INSERT INTO departments (department_name)
VALUES  ("Executive"),
        ("Sales"),
        ("Marketing"),
        ("Legal"),
        ("Engineering"),
        ("Maintenance"),
        ("Operations"),
        ("Accounting");

INSERT INTO roles (title, salary, department_id)
VALUES  ("Director King", 30000000, 1),
        ("Sales Manager", 100000, 2),
        ("Salesperson", 50000, 2),
        ("Marketing Manager", 120000, 3),
        ("Marketing Associate", 45000, 3),
        ("Legal Team Manager", 200000, 4),
        ("Lawyer", 150000, 4),
        ("Engineering Manager", 280000, 5),
        ("Staff Engineer", 200000, 5),
        ("Software Engineer", 160000, 5),
        ("Maintenance Manager", 150000, 6),
        ("Maintenance Technician", 110000, 6),
        ("Operations Manager", 145000, 7),
        ("Operations Associate", 65000, 7),
        ("Account Manager", 125000, 8),
        ("Accountant", 85000, 8);

INSERT INTO employees (first_name, last_name, role_id, manager_id)
VALUES  ("Felon", "Tusk", 1, NULL),
        ("Subhan", "Peck", 2, 1),
        ("Nell", "Reid", 3, 2),
        ("Rosalie", "Kramer", 4, 1),
        ("Angus", "Hewitt", 5, 4),
        ("Abdul", "Dunlap", 6, 1),
        ("Philippa", "Glenn", 7, 6),
        ("Athena", "Rhodes", 7, 6),
        ("Bianca", "Hamilton", 8, 1),
        ("Keelan", "Bryant", 9, 9),
        ("Yash", "Harrell", 10, 9),
        ("Mattie", "Romero", 11, 1),
        ("Lily-Mae", "Benton", 12, 12),
        ("Naomi", "Aguirre", 12, 12),
        ("Joanna", "Farley", 13, 1),
        ("Anas", "Stephenson", 14, 15),
        ("Milan", "Weiss", 14, 15),
        ("Henrietta", "Slater", 14, 15),
        ("Pablo", "Nguyen", 15, 1),
        ("Gregory", "Mitchell", 16, 19),
        ("Niamh", "Sheppard", 16, 19);